# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  lane :generate_mr do
    puts "Generating moko resources..."
    sh "cd ../../ && ./gradlew :shared:generateMR"
  end

  lane :rm_resource_bundle do
    puts "Removing stale shared.bundle..."
    sh "cd ../ && rm -rf Resources/shared.bundle"
  end

  lane :cp_resource_bundle do |options|
    arch = options[:arch]
    configuration = options[:configuration]
    puts "Copying build shared.bundle..."

    sh "cd ../ && cp -R '../shared/build/bin/ios#{arch.capitalize}/#{configuration.downcase}Framework/Shared.framework/Notizen:shared.bundle' Resources/shared.bundle"
  end

  lane :link_framework do |options|
    arch = options[:arch]
    configuration = options[:configuration]
    puts "Linking framework..."

    sh "cd ../../ && ./gradlew link#{configuration.capitalize}FrameworkIos#{arch.capitalize}"
  end

  lane :rm_shared_framework do
    puts "Removing stale shared XC framework..."
    sh "cd ../ && rm -rf Frameworks/Shared.framework"
  end

  lane :cp_shared_framework do |options|
    arch = options[:arch]
    configuration = options[:configuration]
    puts "Copying build shared XC framework..."

    sh "cd ../ && cp -R ../shared/build/bin/ios#{arch.capitalize}/#{configuration.downcase}Framework/Shared.framework Frameworks/Shared.framework"
  end

  lane :run_tuist do
    puts "Running Tuist project generation..."
    sh "cd ../ && tuist clean && tuist install && tuist generate"
  end

  # arch options: X64 (Intel Simulator), SimulatorArm64 (Apple Silicon Simulator), Arm64 (iPhone)
  # configuration options: Debug, Release
  lane :build_xc_project do |options|
    arch = options[:arch]
    configuration = options[:configuration] || "Debug"
    puts "Building KMP Shared.framework with arch:#{arch.downcase} and configuration:#{configuration.downcase}"

    # 1. Generate new resouces and framework
    generate_mr
    link_framework(arch: arch, configuration: configuration)

    # 2. Remove old folders
    rm_resource_bundle
    rm_shared_framework

    # 3. Copy new builds
    cp_resource_bundle(arch: arch, configuration: configuration)
    cp_shared_framework(arch: arch, configuration: configuration)

    # 4. Generate Xcode project
    run_tuist
  end
end
