# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Build KMP Shared.framework for Intel simulator"
  lane :build_intel_simulator do |options|
    configuration = options[:configuration] || "Debug"

    # Generate resources
    sh "cd ../../ && ./gradlew :shared:generateMR"
    sh "cd ../ && cp -R '../shared/build/bin/iosX64/#{configuration.downcase}Framework/Shared.framework/Notizen:shared.bundle' Resources/shared.bundle"

    # Remove old bundle
    sh "cd ../ && rm -rf Resources/shared.bundle"

    # Copy the generated bundle manually
    sh "cd ../ && cp -R '../shared/build/bin/iosX64/#{configuration.downcase}Framework/Shared.framework/Notizen:shared.bundle' Resources/shared.bundle"
    
    # Build the framework
    sh "cd ../../ && ./gradlew :shared:assembleIntelSimulatorFramework"

    # Remove the old framework
    sh "cd ../ && rm -rf Frameworks/Shared.framework"
    
    # Copy the framework
    sh "cd ../ && cp -R ../shared/build/bin/iosX64/#{configuration.downcase}Framework/Shared.framework Frameworks/Shared.framework"

    sh "echo 'Success! Run tuist generate (optionally tuist clean && tuist install) to run in Xcode.'"
  end

  desc "Build KMP Shared.framework for Apple Silicon simulator"
  lane :build_silicon_simulator do |options|
    configuration = options[:configuration] || "Debug"
  
    # Generate resources
    sh "cd ../../ && ./gradlew :shared:generateMR"
    sh "cd ../../ && ./gradlew :shared:assembleSiliconSimulatorFramework"
  
    # Remove old bundle
    sh "cd ../ && rm -rf Resources/shared.bundle"
  
    # Copy the generated bundle manually
    sh "cd ../ && cp -R '../shared/build/bin/iosSimulatorArm64/#{configuration.downcase}Framework/Shared.framework/Notizen:shared.bundle' Resources/shared.bundle"
  
    # Remove old framework
    sh "cd ../ && rm -rf Frameworks/Shared.framework"
  
    # Copy the framework
    sh "cd ../ && cp -R ../shared/build/bin/iosSimulatorArm64/#{configuration.downcase}Framework/Shared.framework Frameworks/Shared.framework"
  
    sh "echo 'Success! Run tuist generate (optionally tuist clean && tuist install) to run in Xcode.'"
  end

  desc "Build KMP Shared.framework for physical device"
  lane :build_physical_device do |options|
    configuration = options[:configuration] || "Debug"
      
    # Generate resources
    sh "cd ../../ && ./gradlew :shared:generateMR"
    sh "cd ../../ && ./gradlew :shared:assembleSiliconSimulatorFramework"
  
    # Remove old bundle
    sh "cd ../ && rm -rf Resources/shared.bundle"
  
    # Copy the generated bundle manually
    sh "cd ../ && cp -R '../shared/build/bin/iosArm64/#{configuration.downcase}Framework/Shared.framework/Notizen:shared.bundle' Resources/shared.bundle"
  
    # Build the framework
    sh "cd ../../ && ./gradlew :shared:assembleSiliconSimulatorFramework"

    # Copy the framework
    sh "cd ../ && cp -R ../shared/build/bin/iosArm64/#{configuration.downcase}Framework/Shared.framework Frameworks/Shared.framework"

    sh "echo 'Success! Run tuist generate (optionally tuist clean && tuist install) to run in Xcode.'"
  end
end
